edubd/edubd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('library',include('libraries.urls')),
    path('',include('hostels.urls')),
    path('transport/',include('transports.urls')),
    path('leave/',include('leave.urls')),
    path('announcement/',include('announcement.urls')),
    path('frontoffice/',include('frontoffice.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

edubd/transports/urls.py
from django.urls import path
from .views import driver, vehicle, stopage, route, schedule, fare
app_name = 'transport'

urlpatterns = [
    #driver
    path('drivers/',driver.DriversView.as_view(), name="drivers"),
    path('add_driver/',driver.AddDriverView.as_view(), name="add_driver"),
    path('edit_driver/<int:pk>',driver.EditDriverView.as_view(), name="edit_driver"),
    path('delete_driver/<int:pk>',driver.DeleteDriverView.as_view(), name="delete_driver"),
    
    
    #vehicle
    path('vehicles/',vehicle.VehiclesView.as_view(), name="vehicles"),
    path('add_vehicle/',vehicle.AddVehicleView.as_view(), name="add_vehicle"),
    path('edit_vehicle/<int:pk>',vehicle.EditVehicleView.as_view(), name="edit_vehicle"),
    path('delete_vehicle/<int:pk>',vehicle.DeleteVehicleView.as_view(), name="delete_vehicle"),
    #vehicles_driver
    path('vehicle_drivers/<int:pk>',vehicle.VehicleDriversView.as_view(), name="vehicle_drivers"),
    path('add_vehicle_driver/<int:pk>',vehicle.AddVehicleDriverView.as_view(), name="add_vehicle_driver"),
    path('delete_vehicle_driver/<int:vehicle>/<int:driver>',vehicle.DeleteVehicleDriverView.as_view(), name="delete_vehicle_driver_vehicle_driver"),
    #ajax
    path('get_driver',vehicle.GetDriverView.as_view(), name="get_driver"),

    #stopage
    path('stopages/',stopage.StopageView.as_view(), name="stopages"),
    path('add_stopage/',stopage.AddStopageView.as_view(), name="add_stopage"),
    path('edit_stopage/<int:pk>',stopage.EditStopageView.as_view(), name="edit_stopage"),
    path('delete_stopage/<int:pk>',stopage.DeleteStopageView.as_view(), name="delete_stopage"),
    
    
    #route
    path('routes/',route.RouteView.as_view(), name="routes"),
    path('add_route/',route.AddRouteView.as_view(), name="add_route"),
    path('edit_route/<int:pk>',route.EditRouteView.as_view(), name="edit_route"),
    path('delete_route/<int:pk>',route.DeleteRouteView.as_view(), name="delete_route"),
    
    #schedule
    path('schedules/',schedule.ScheduleView.as_view(), name="schedules"),
    path('add_schedule/',schedule.AddScheduleView.as_view(), name="add_schedule"),
    path('edit_schedule/<int:pk>',schedule.EditScheduleView.as_view(), name="edit_schedule"),
    path('delete_schedule/<int:pk>',schedule.DeleteScheduleView.as_view(), name="delete_schedule"),
    #schedule_stopage
    path('schedule_stopages/<int:pk>',schedule.ScheduleStopageView.as_view(), name="schedule_stopages"),
    path('add_schedule_stopage/<int:pk>',schedule.AddScheduleStopageView.as_view(), name="add_schedule_stopage"),
    path('delete_schedule_stopage/<int:pk>',schedule.DeleteScheduleStopageView.as_view(), name="delete_schedule_stopage"),
    #schedule_member
    path('schedule_members/<int:pk>',schedule.ScheduleMemberView.as_view(), name="schedule_members"),
    path('add_schedule_member/<int:pk>',schedule.AddScheduleMemberView.as_view(), name="add_schedule_member"),
    path('delete_schedule_member/<int:pk>',schedule.DeleteScheduleMemberView.as_view(), name="delete_schedule_member"),

    #fare
    path('fares/',fare.FareView.as_view(), name="fares"),
    path('add_fare/',fare.AddFareView.as_view(), name="add_fare"),
    path('edit_fare/<int:pk>',fare.EditFareView.as_view(), name="edit_fare"),
    path('delete_fare/<int:pk>',fare.DeleteFareView.as_view(), name="delete_fare"),
]

edubd/transports/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# Create your models here.


#-----------------------driver --------------------
class Driver(models.Model):
    name=models.CharField(max_length=200)
    phone=models.CharField(max_length=200)
    driving_licence=models.CharField(max_length=200)
    driving_licence_validity=models.DateField(null=True)
    age=models.CharField(max_length=200)
    gender=models.CharField(max_length=200)
    address=models.TextField(max_length=200, null=True)
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name 

#-----------------------vehicle --------------------
class Vehicle(models.Model):
    name=models.CharField(max_length=200)
    number=models.CharField(max_length=200)
    model=models.CharField(max_length=200)
    license=models.CharField(max_length=200)
    year_made=models.DateField(null=True)
    driver=models.ManyToManyField(Driver, blank=True)
    description=models.TextField(max_length=200, null=True, blank=True)
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name 


#-----------------------stopage --------------------
class Stopage(models.Model):
    name=models.CharField(max_length=200)
    fare=models.FloatField(null=True, blank=True)
    lat=models.CharField(max_length=200, null=True, blank=True)
    long=models.CharField(max_length=200, null=True, blank=True)
    address=models.TextField(max_length=200, null=True, blank=True)
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name 

#-----------------------route --------------------
class Route(models.Model):
    name=models.CharField(max_length=200)
    start_point=models.ForeignKey(Stopage,null=True, on_delete=models.SET_NULL,related_name='start_point')
    end_point=models.ForeignKey(Stopage,null=True, on_delete=models.SET_NULL, related_name='end_point')
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


#-----------------------schedule--------------------
class Schedule(models.Model):
    route=models.ForeignKey(Route,null=True, on_delete=models.SET_NULL)
    vehicle=models.ForeignKey(Vehicle,null=True, on_delete=models.SET_NULL)
    driver=models.ForeignKey(Driver,null=True, on_delete=models.SET_NULL)
    start_time=models.TimeField(null=True)
    end_time=models.TimeField(null=True)

    
#-----------------------schedule stopage--------------------
class ScheduleStopage(models.Model):
    schedule=models.ForeignKey(Schedule,null=True,blank=True, on_delete=models.SET_NULL)
    stopage=models.ForeignKey(Stopage,null=True, on_delete=models.SET_NULL)
    reach_time=models.TimeField(null=True)
    leave_time=models.TimeField(null=True)


#-----------------------fare--------------------
class Fare(models.Model):
    start_stopage=models.ForeignKey(Stopage,null=True, on_delete=models.SET_NULL,related_name='start_stopage')
    end_stopage=models.ForeignKey(Stopage,null=True, on_delete=models.SET_NULL, related_name='end_stopage')
    fare=models.FloatField(null=True)
    date_created=models.DateTimeField(auto_now_add=True)


#-----------------------schedule member--------------------
class ScheduleMember(models.Model):
    user=models.ForeignKey(User,null=True, on_delete=models.SET_NULL)
    schedule=models.ForeignKey(Schedule,null=True,blank=True, on_delete=models.SET_NULL)
    date_created=models.DateTimeField(auto_now_add=True)

edubd/transports/views/driver.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.urls import reverse
from ..models import Driver
from ..form import DriverForm
from django.contrib import messages
# Create your views here.

class DriversView(View):
    def get(self,request):
        drivers=Driver.objects.all().order_by('-id')
        contex = {'drivers':drivers}
        return render(request, 'driver/index.html',contex)

class AddDriverView(View):
    def get(self,request):
        form = DriverForm()
        context = {'form':form}
        return render(request, 'driver/create.html',context)
    def post(self,request):
        if request.method=='POST':
            driver=request.POST
            form = DriverForm(request.POST) 
            if form.is_valid():
                driver=form.save()
                messages.success(request,'Data store successfull',extra_tags='success')
                return redirect(reverse('transport:drivers'))
    

class EditDriverView(View):
    def get(self,request,pk):
        driver=Driver.objects.get(id=pk)
        form = DriverForm(instance=driver)
        context={'form':form}
        return render(request, 'driver/create.html',context)
    def post(self,request,pk):
        driver=Driver.objects.get(id=pk)
        if request.method=='POST':
            form = DriverForm(request.POST, instance=driver)
            if form.is_valid():
                form.save()
                messages.success(request,'Data update successfull',extra_tags='success')
                return redirect(reverse('transport:drivers'))
    

class DeleteDriverView(View):
    def get(self,request,pk):
        driver=Driver.objects.get(id=pk)
        driver.delete()
        messages.success(request,'Data delete successfull',extra_tags='success')
        return redirect(reverse('transport:drivers'))

edubd/transports/views/fare.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.urls import reverse
from ..models import Fare
from ..form import FareForm
from django.contrib import messages 
# Create your views here.


class FareView(View):
    def get(self,request):
        fares=Fare.objects.all().order_by('-id')
        contex = {'fares':fares}
        return render(request, 'fare/index.html',contex)

class AddFareView(View):
    def get(self,request):
        form = FareForm()
        context = {'form':form}
        return render(request, 'fare/create.html',context)
    def post(self,request):
        fare=request.POST
        form = FareForm(request.POST) 
        if form.is_valid():
           fare=form.save()
           messages.success(request,'Data store successfull',extra_tags='success')
           return redirect(reverse('transport:fares'))
    

class EditFareView(View):
    def get(self,request,pk):
        fare=Fare.objects.get(id=pk)
        form = FareForm(instance=fare)
        context={'form':form}
        return render(request, 'fare/create.html',context)
    def post(self,request,pk):
        fare=Fare.objects.get(id=pk)
        form = FareForm(request.POST, instance=fare)
        if form.is_valid():
           form.save()
           messages.success(request,'Data update successfull',extra_tags='success')
           return redirect(reverse('transport:fares'))
    

class DeleteFareView(View):
    def get(self,request,pk):
        fare=Fare.objects.get(id=pk)
        fare.delete()
        messages.success(request,'Data delete successfull',extra_tags='success')
        return redirect(reverse('transport:fares'))

edubd/transports/views/route.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.urls import reverse
from ..models import Route
from ..form import RouteForm
from django.contrib import messages 
# Create your views here.

class RouteView(View):
    def get(self,request):
        routes=Route.objects.all().order_by('-id')
        contex = {'routes':routes}
        return render(request, 'route/index.html',contex)

class AddRouteView(View):
    def get(self,request):
        form = RouteForm()
        context = {'form':form}
        return render(request, 'route/create.html',context)
    def post(self,request):
        if request.method=='POST':
            route=request.POST
            form = RouteForm(request.POST) 
            if form.is_valid():
                route=form.save()
                messages.success(request,'Data store successfull',extra_tags='success')
                return redirect(reverse('transport:routes'))
    

class EditRouteView(View):
    def get(self,request,pk):
        route=Route.objects.get(id=pk)
        form = RouteForm(instance=route)
        context={'form':form}
        return render(request, 'route/create.html',context)
    def post(self,request,pk):
        route=Route.objects.get(id=pk)
        if request.method=='POST':
            form = RouteForm(request.POST, instance=route)
            if form.is_valid():
                form.save()
                messages.success(request,'Data update successfull',extra_tags='success')
                return redirect(reverse('transport:routes'))
    

class DeleteRouteView(View):
    def get(self,request,pk):
        route=Route.objects.get(id=pk)
        route.delete()
        messages.success(request,'Data delete successfull',extra_tags='success')
        return redirect(reverse('transport:routes'))

edubd/transports/views/stopage.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.urls import reverse
from ..models import Stopage
from ..form import StopageForm
from django.contrib import messages 
# Create your views here.


class StopageView(View):
    def get(self,request):
        stopages=Stopage.objects.all().order_by('-id')
        contex = {'stopages':stopages}
        return render(request, 'stopage/index.html',contex)

class AddStopageView(View):
    def get(self,request):
        form = StopageForm()
        context = {'form':form}
        return render(request, 'stopage/create.html',context)
    def post(self,request):
        if request.method=='POST':
            stopage=request.POST
            form = StopageForm(request.POST) 
            if form.is_valid():
                stopage=form.save()
                messages.success(request,'Data store successfull',extra_tags='success')
                return redirect(reverse('transport:stopages'))
    
class EditStopageView(View):
    def get(self,request,pk):
        stopage=Stopage.objects.get(id=pk)
        form = StopageForm(instance=stopage)
        context={'form':form}
        return render(request, 'stopage/create.html',context)
    def post(self,request,pk):
        stopage=Stopage.objects.get(id=pk)
        if request.method=='POST':
            form = StopageForm(request.POST, instance=stopage)
            if form.is_valid():
                form.save()
                messages.success(request,'Data update successfull',extra_tags='success')
                return redirect(reverse('transport:stopages'))
        

class DeleteStopageView(View):
    def get(self,request,pk):
        stopage=Stopage.objects.get(id=pk)
        stopage.delete()
        messages.success(request,'Data delete successfull',extra_tags='success')
        return redirect(reverse('transport:stopages'))

edubd/transports/templates/schedule/add_member.html
{%  extends 'author/base.html' %}

{% block content %}

		<br>

		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card card-body">
					<h5>Member</h5>
				</div>
				<div class="card card-body">
					<form action="" method="POST">
						{% csrf_token %}
						<div class="row " >
							<div class="col-md-12">
								<div class="form-group">
									<label for="exampleInputEmail1">Member</label>
									{{form.user}}
									<span class="text-danger">{{form.errors.user}}</span>
								</div>
							</div>
							
						</div>
						<button type="submit" class="btn btn-success">Submit</button>
					</form>
				</div>
			</div>
			
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script>
		$(document).ready(function() {
			$('#id_user').find("option:first-child").removeAttr('selected');
		});
	</script>
{% endblock content %}

edubd/transports/templates/schedule/add_stopage.html
{%  extends 'author/base.html' %}

{% block content %}

		<br>

		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card card-body">
					<h5>Stopage</h5>
				</div>
				<div class="card card-body">
					<form action="" method="POST">
						{% csrf_token %}
						<div class="row stopage" >
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Stopage</label>
									{{form.stopage}}
									<span class="text-danger">{{form.errors.stopage}}</span>
								</div>
							</div>
							
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Reach Time</label>
									{{form.reach_time}}
									<span class="text-danger">{{form.errors.reach_time}}</span>
								</div>
							</div>
						
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Leave Time</label>
									{{form.leave_time}}
									<span class="text-danger">{{form.errors.leave_time}}</span>
								</div>
								
							</div>
							
						</div>
							<div class="more_div"></div>
							<button id="more" type="button" class="btn btn-success float-right ">+</button>
						<div class="row ">
							<div class="col-md-12"></div>
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</form>
					</form>
				</div>
			</div>
			
		</div>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		
		<script>
			$(document).ready(function() {
				var i = 1;
				console.log('aa');
				$("#more").click(function(){
					i++;
					console.log('aa');
					$(".more_div").append('<div class="row stopage"><div class="col-md-4"><div class="form-group"><label for="exampleInputEmail1">Stopage</label><select class="form-control select2" name="stopage" required><option value="">Select </option>{% for row in stopage %}<option value="{{row.id}}">{{row.name}} </option>{% endfor %}</select></div></div><div class="col-md-4"><div class="form-group"><label for="exampleInputEmail1">Reach Time</label>{{form.reach_time}}<span class="text-danger">{{form.errors.reach_time}}</span></div></div><div class="col-md-3"><div class="form-group"><label for="exampleInputEmail1">Leave Time</label>{{form.leave_time}}<span class="text-danger">{{form.errors.leave_time}}</span></div></div><div class="col-md-1" style="    margin-top: 35px;"><a id="remove_row-'+i+'" class="btn btn-danger btn-sm delete-record float-right"><i class="fa fa-times" title="remove"></i></a></div></div>');
					$(".more_div").on('click', '.delete-record', function(){
						$(this).closest(".stopage").remove();
					   
					});
				}); 
			}); 
		</script>
{% endblock content %}

edubd/transports/templates/schedule/create.html
{%  extends 'author/base.html' %}

{% block content %}

		<br>

		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card card-body">
					<h5>Schedule</h5>
				</div>
				<div class="card card-body">
					<form action="" method="POST">
						{% csrf_token %}
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Route</label>
									{{form.route}}
									<span class="text-danger">{{form.errors.route}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Vehicle</label>
									{{form.vehicle}}
									<span class="text-danger">{{form.errors.vehicle}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Driver</label>
										{% if check == 1 %}
											{{form.driver}}
										{% else %}
											<select class="form-control select2" name="driver" id="driver">
											</select>
										{% endif %}
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="exampleInputEmail1">Start Time</label>
									{{form.start_time}}
									<span class="text-danger">{{form.errors.start_time}}</span>
								</div>
							</div>
						
							<div class="col-md-6">
								<div class="form-group">
									<label for="exampleInputEmail1">End Time</label>
									{{form.end_time}}
									<span class="text-danger">{{form.errors.end_time}}</span>
								</div>
								
							</div>
							
						</div>
						<button type="submit" class="btn btn-success">Submit</button>
						
					</form>
				</div>
			</div>
			
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		
		<script>
			$(document).ready(function() {
				$("#id_vehicle").change(function(){
					var id = $(this).val();
					$.ajax({
						type:'GET',
						url:'{% url 'transport:get_driver' %}',
						data:{vehicle:id},
						success:function(data){
							$('#driver').html(data)
						},
						error:function(){
							console.log('error');
						}
					});
				});
			});
		</script>
{% endblock content %}

edubd/transports/templates/schedule/get_driver.html
<option value="">Select</option>
{% for row in drivers  %}
    <option value="{{row.id}}">{{row.name}}</option>
{% endfor %}

edubd/transports/templates/schedule/index.html
{% extends "author/base.html" %}

{% block content %}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<h5>:</h5>
		
		
		<hr>
		<div class="card card-header">
		<h1>Schedule
			<a class="btn btn-primary  float-right" href="{% url 'transport:add_schedule' %}"> + Create Schedule</a></h1>
		</div>
		<div class="card card-body"> 
			<table  class="display table table-bordered table-hover table-striped datatable" style="width:100%">
				<thead>
				<tr>
					<th>Serial</th>
					<th>Route</th>
					<th>Vehicle</th>
					<th>Vehicle Number</th>
					<th>Driver</th>
					<th>Start Time</th>
					<th>End Time</th>
					<th>Action</th>
				</thead>
				<tbody>
				{% for row in schedules  %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td>{{row.route}}</td>
						<td>{{row.vehicle}}</td>
						<td>{{row.vehicle.number}}</td>
						<td>{{row.driver}}</td>
						<td>{{row.start_time}}</td>
						<td>{{row.end_time}}</td>
						<td>
						<a href="{% url 'transport:schedule_members' row.id %}" class="btn btn-warning" title="member"><i class="fa fa-users"></i></a>
						<a href="{% url 'transport:schedule_stopages' row.id %}" class="btn btn-success" title="stopage"><i class="fa fa-ban"></i></a>
						<a href="{% url 'transport:edit_schedule' row.id %}" class="btn btn-info"><i class="fa fa-edit"></i></a>
						<a onclick='return confirm("Are you sure you want to do this?")' href="{% url 'transport:delete_schedule' row.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a></td>
					</tr>
				{% endfor %}

			</tbody>
			</table>
		</div>
	</div>

	

</div>
  
{% endblock  %}

edubd/transports/templates/schedule/member.html
{% extends "author/base.html" %}

{% block content %}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<h5>:</h5>
		
		
		<hr>
		<div class="card card-header">
		<h1>Member
			<a class="btn btn-primary  float-right" href="{% url 'transport:add_schedule_member' schedule %} "> + Create Member</a></h1>
		</div>
		<div class="card card-body"> 
			<table  class="display table table-bordered table-hover table-striped datatable" style="width:100%">
				<thead>
				<tr>
					<th>Serial</th>
					<th>User</th>
					<th>Schedule</th>
					<th>Route</th>
					<th>Action</th>
				</thead>
				<tbody>
				{% for row in members  %}
					<tr>
						<td>{{forloop.counter}}</td>
						
						<td>
							<span class="font-weight-bold"> Name: </span> {{row.user.first_name}}, <br>
							<span class="font-weight-bold"> Email: </span> {{row.user.email}}, <br>
						</td>
						<td>
						<span class="font-weight-bold"> Vehicle: </span> {{row.schedule.vehicle.name}}, <br>
						<span class="font-weight-bold"> Driver: </span> {{row.schedule.driver.name}}, <br>
						<span class="font-weight-bold"> Start Time: </span> {{row.schedule.start_time}}, <br>
						<span class="font-weight-bold"> End Time: </span> {{row.schedule.end_time}}, <br>
						</td>
						<td>
							<span class="font-weight-bold"> Route: </span> {{row.schedule.route}}, <br>
							<span class="font-weight-bold"> Start Point: </span> {{row.schedule.route.start_point}}, <br>
							<span class="font-weight-bold"> End Point: </span> {{row.schedule.route.end_point}}, <br>
						</td>
						<td>
						<a onclick='return confirm("Are you sure you want to do this?")' href="{% url 'transport:delete_schedule_member' row.id %}" class="btn btn-danger">Delete</a></td>
					</tr>
				{% endfor %}

			</tbody>
			</table>
		</div>
	</div>

	

</div>
  
{% endblock  %}

edubd/transports/templates/schedule/stopage.html
{% extends "author/base.html" %}

{% block content %}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<h5>:</h5>
		
		
		<hr>
		<div class="card card-header">
		<h1>Stopage
			<a class="btn btn-primary  float-right" href="{% url 'transport:add_schedule_stopage' schedule %} "> + Create Stopage</a></h1>
		</div>
		<div class="card card-body"> 
			<table  class="display table table-bordered table-hover table-striped datatable" style="width:100%">
				<thead>
				<tr>
					<th>Serial</th>
					<th>Name</th>
					<th>Lat</th>
					<th>Long</th>
					<th>Fare</th>
					<th>Address</th>
					<th>Reach Time</th>
					<th>Leave Time</th>
					<th>Action</th>
				</thead>
				<tbody>
				{% for row in stopages  %}
					<tr>
						<td>{{forloop.counter}}</td>
						
						<td>{{row.stopage.name}}</td>
						<td>{{row.stopage.lat}}</td>
						<td>{{row.stopage.long}}</td>
						<td>{{row.stopage.fare}}</td>
						<td>{{row.stopage.address}}</td>
						<td>{{row.reach_time}}</td>
						<td>{{row.leave_time}}</td>
						<td>
						<a onclick='return confirm("Are you sure you want to do this?")' href="{% url 'transport:delete_schedule_stopage' row.id %}" class="btn btn-danger">Delete</a></td>
					</tr>
				{% endfor %}

			</tbody>
			</table>
		</div>
	</div>

	

</div>
  
{% endblock  %}