edubd/edubd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('library',include('libraries.urls')),
    path('',include('hostels.urls')),
    path('transport/',include('transports.urls')),
    path('leave/',include('leave.urls')),
    path('announcement/',include('announcement.urls')),
    path('frontoffice/',include('frontoffice.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

edubd/frontoffice/urls.py
from django.urls import path
from .views import visitorbook, phonecalllog, postaldispatch, postalreceive, complain
app_name = 'frontoffice'
urlpatterns = [
    #visitor_book
    path('visitorbooks/',visitorbook.VisitorbookView.as_view(), name="visitorbooks"),
    path('visitorbook/<int:pk>',visitorbook.DetailVisitorbookView.as_view(), name="visitorbook"),
    path('add_visitorbook/',visitorbook.AddVisitorbookView.as_view(), name="add_visitorbook"),
    path('edit_visitorbook/<int:pk>',visitorbook.EditVisitorbookView.as_view(), name="edit_visitorbook"),
    path('delete_visitorbook/<int:pk>',visitorbook.DeleteVisitorbookView.as_view(), name="delete_visitorbook"),
    #ajax data
    path('get_user/',visitorbook.GetUserView.as_view(), name="get_user"),
    
    #phonecalllog
    path('phonecalllogs/',phonecalllog.PhonecalllogView.as_view(), name="phonecalllogs"),
    path('phonecalllog/<int:pk>',phonecalllog.DetailPhonecalllogView.as_view(), name="phonecalllog"),
    path('add_phonecalllog/',phonecalllog.AddPhonecalllogView.as_view(), name="add_phonecalllog"),
    path('edit_phonecalllog/<int:pk>',phonecalllog.EditPhonecalllogView.as_view(), name="edit_phonecalllog"),
    path('delete_phonecalllog/<int:pk>',phonecalllog.DeletePhonecalllogView.as_view(), name="delete_phonecalllog"),
    
    #postaldispatch
    path('postaldispatchs/',postaldispatch.PostaldispatchView.as_view(), name="postaldispatchs"),
    path('add_postaldispatch/',postaldispatch.AddPostaldispatchView.as_view(), name="add_postaldispatch"),
    path('edit_postaldispatch/<int:pk>',postaldispatch.EditPostaldispatchView.as_view(), name="edit_postaldispatch"),
    path('delete_postaldispatch/<int:pk>',postaldispatch.DeletePostaldispatchView.as_view(), name="delete_postaldispatch"),
    
    #postalreceive
    path('postalreceives/',postalreceive.PostalreceiveView.as_view(), name="postalreceives"),
    path('add_postalreceive/',postalreceive.AddPostalreceiveView.as_view(), name="add_postalreceive"),
    path('edit_postalreceive/<int:pk>',postalreceive.EditPostalreceiveView.as_view(), name="edit_postalreceive"),
    path('delete_postalreceive/<int:pk>',postalreceive.DeletePostalreceiveView.as_view(), name="delete_postalreceive"),
    
    #complain
    path('complains/',complain.ComplainView.as_view(), name="complains"),
    path('complain/<int:pk>',complain.DetailComplainView.as_view(), name="complain"),
    path('add_complain/',complain.AddComplainView.as_view(), name="add_complain"),
    path('edit_complain/<int:pk>',complain.EditComplainView.as_view(), name="edit_complain"),
    path('delete_complain/<int:pk>',complain.DeleteComplainView.as_view(), name="delete_complain"),
]

edubd/frontoffice/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError

import mimetypes
import os
# Create your models here.


def validate_image(image):
    file_size = image.file.size
    limit_mb = 2
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError("Max size of file is %s KB" % limit_mb)

def validate_file(file):
    ext = os.path.splitext(file.name)[1]  # [0] returns path+filename
    valid_extensions = ['.pdf','.doc', '.docx', '.jpg', '.png', '.ppt', '.pptx', '.text']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Please choose these  %s file type' % valid_extensions)
    file_size = file.file.size
    limit_mb = 250
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError("Max size of file is %s KB" % limit_mb)

class Visitorbook(models.Model):
    purpose=models.CharField(max_length=200, null=True )
    name=models.CharField(max_length=200, null=True )
    phone=models.CharField(max_length=200, null=True )
    meet_user_type=models.ForeignKey(Group , null=True  , on_delete=models.SET_NULL)
    meet_user=models.ForeignKey(User , null=True  , on_delete=models.SET_NULL)
    id_card=models.CharField(max_length=200, null=True )
    date=models.DateField(null=True)
    in_time=models.TimeField(null=True)
    out_time=models.TimeField(null=True, blank=True)
    note=models.TextField(null=True,blank=True)
    attachment=models.FileField(upload_to='visitorbook', null=True, blank=True,validators=[validate_file])
    image=models.ImageField(upload_to='visitorbook', null=True, validators=[validate_image])
    #image=FSCameraField(format='jpg')
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Phonecalllog(models.Model):
    CALL_TYPE = (
        (1, 'Incoming'),
        (2, 'Outgoing'),
    )
    name=models.CharField(max_length=200, null=True )
    phone=models.CharField(max_length=200, null=True )
    call_duration=models.CharField(max_length=200, null=True )
    date=models.DateField(null=True)
    followup=models.DateField(null=True, blank=True)
    call_type=models.IntegerField(null=True, choices=CALL_TYPE)
    description=models.TextField(null=True,blank=True)
    note=models.TextField(null=True,blank=True)
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Postaldispatch(models.Model):
    receiver=models.CharField(max_length=200, null=True )
    sender=models.CharField(max_length=200, null=True )
    referance=models.CharField(max_length=200, null=True )
    dispatch_date=models.DateField(null=True)
    address=models.TextField(null=True)
    note=models.TextField(null=True,blank=True)
    attachment=models.FileField(upload_to='postal', null=True, blank=True,validators=[validate_file])
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.receiver

class Postalreceive(models.Model):
    receiver=models.CharField(max_length=200, null=True )
    sender=models.CharField(max_length=200, null=True )
    referance=models.CharField(max_length=200, null=True )
    receive_date=models.DateField(null=True)
    address=models.TextField(null=True)
    note=models.TextField(null=True,blank=True)
    attachment=models.FileField(upload_to='postal', null=True, blank=True,validators=[validate_file])
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.receiver

class Complain(models.Model):
    TYPE = (
        ('Fees', 'Fees'),
        ('Study', 'Study'),
        ('Teacher', 'Teacher'),
        ('Sports', 'Sports'),
        ('Transport', 'Transport'),
        ('Hostel', 'Hostel'),
        ('Front Site', 'Front Site'),
        ('Others', 'Others'),
    )
    complain_type=models.CharField(max_length=100, null=True, choices=TYPE )
    complain_by=models.ForeignKey(User , null=True  , on_delete=models.SET_NULL)
    phone=models.CharField(max_length=200, null=True )
    date=models.DateField(null=True)
    description=models.TextField(null=True,blank=True)
    action_taken=models.TextField(null=True,blank=True)
    assigned=models.ForeignKey(User , null=True, on_delete=models.SET_NULL, related_name='assigned')
    note=models.TextField(null=True,blank=True)
    attachment=models.FileField(upload_to='postal', null=True, blank=True,validators=[validate_file])
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.complain_type

edubd/frontoffice/views/complain.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.models import User, Group
from django.urls import reverse
from ..models import Complain
from ..form import ComplainForm
from django.contrib import messages
import datetime
from django.utils import formats


# Create your views here.

# Create your views here.

class ComplainView(View):
    def get(self,request):
        complain=Complain.objects.all().order_by('-id')
        contex = {'complain':complain}
        return render(request, 'complain/index.html',contex)

class AddComplainView(View):
    def get(self,request):
        form = ComplainForm()
        context = {'form':form, 'check':0}
        return render(request, 'complain/create.html',context)
    def post(self,request):
        complain=request.POST
        form = ComplainForm(request.POST, request.FILES) 
        if form.is_valid():
            complain=form.save()
            messages.success(request,'Data store successfull',extra_tags='success')
            return redirect(reverse('frontoffice:complains'))
    

class DetailComplainView(View):
    def get(self,request,pk):
        complain=Complain.objects.get(id=pk)
        context={'complain':complain}
        return render(request, 'complain/detail.html',context)

class EditComplainView(View):
    def get(self,request,pk):
        complain=Complain.objects.get(id=pk)
        form = ComplainForm(instance=complain)
        context={'form':form, 'check':1}
        return render(request, 'complain/create.html',context)
    def post(self,request,pk):
        complain=Complain.objects.get(id=pk)
        form = ComplainForm(request.POST, request.FILES, instance=complain)
        if form.is_valid():
            form.save()
            messages.success(request,'Data update successfull',extra_tags='success')
            return redirect(reverse('frontoffice:complains'))
    

class DeleteComplainView(View):
    def get(self,request,pk):
        complain=Complain.objects.get(id=pk)
        complain.delete()
        messages.success(request,'Data delete successfull',extra_tags='success')
        return redirect(reverse('frontoffice:complains'))



class GetUserView(View):
    def get(self,request):
        id=request.GET.get('id')
        users=User.objects.filter(groups=id).all()
        print(users)
        context={'users':users}
        return render(request, 'complain/get_user.html',context)

edubd/frontoffice/views/phonecalllog.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.models import User, Group
from django.urls import reverse
from ..models import Phonecalllog
from ..form import PhonecalllogForm
from django.contrib import messages
import datetime
from django.utils import formats


# Create your views here.

# Create your views here.

class PhonecalllogView(View):
    def get(self,request):
        phonecalllog=Phonecalllog.objects.all().order_by('-id')
        date=formats.date_format(datetime.datetime.now().date(),'Y-m-d')
        contex = {'phonecalllog':phonecalllog,'date':date}
        return render(request, 'phonecalllog/index.html',contex)

class AddPhonecalllogView(View):
    def get(self,request):
        form = PhonecalllogForm()
        context = {'form':form }
        return render(request, 'phonecalllog/create.html',context)
    def post(self,request):
        phonecalllog=request.POST
        form = PhonecalllogForm(request.POST, request.FILES) 
        if form.is_valid():
            phonecalllog=form.save()
            messages.success(request,'Data store successfull',extra_tags='success')
            return redirect(reverse('frontoffice:phonecalllogs'))
    

class DetailPhonecalllogView(View):
    def get(self,request,pk):
        phonecalllog=Phonecalllog.objects.get(id=pk)
        context={'phonecalllog':phonecalllog}
        return render(request, 'phonecalllog/detail.html',context)

class EditPhonecalllogView(View):
    def get(self,request,pk):
        phonecalllog=Phonecalllog.objects.get(id=pk)
        form = PhonecalllogForm(instance=phonecalllog)
        context={'form':form}
        return render(request, 'phonecalllog/create.html',context)
    def post(self,request,pk):
        phonecalllog=Phonecalllog.objects.get(id=pk)
        form = PhonecalllogForm(request.POST, request.FILES, instance=phonecalllog)
        if form.is_valid():
            form.save()
            messages.success(request,'Data update successfull',extra_tags='success')
            return redirect(reverse('frontoffice:phonecalllogs'))
    

class DeletePhonecalllogView(View):
    def get(self,request,pk):
        phonecalllog=Phonecalllog.objects.get(id=pk)
        phonecalllog.delete()
        messages.success(request,'Data delete successfull',extra_tags='success')
        return redirect(reverse('frontoffice:phonecalllogs'))

edubd/frontoffice/views/postaldispatch.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.models import User, Group
from django.urls import reverse
from ..models import Postaldispatch
from ..form import PostaldispatchForm
from django.contrib import messages
import datetime
from django.utils import formats


# Create your views here.

# Create your views here.

class PostaldispatchView(View):
    def get(self,request):
        postaldispatch=Postaldispatch.objects.all().order_by('-id')
        contex = {'postaldispatch':postaldispatch}
        return render(request, 'postaldispatch/index.html',contex)

class AddPostaldispatchView(View):
    def get(self,request):
        form = PostaldispatchForm()
        context = {'form':form }
        return render(request, 'postaldispatch/create.html',context)
    def post(self,request):
        postaldispatch=request.POST
        form = PostaldispatchForm(request.POST, request.FILES) 
        if form.is_valid():
            postaldispatch=form.save()
            messages.success(request,'Data store successfull',extra_tags='success')
            return redirect(reverse('frontoffice:postaldispatchs'))
    



class EditPostaldispatchView(View):
    def get(self,request,pk):
        postaldispatch=Postaldispatch.objects.get(id=pk)
        form = PostaldispatchForm(instance=postaldispatch)
        context={'form':form}
        return render(request, 'postaldispatch/create.html',context)
    def post(self,request,pk):
        postaldispatch=Postaldispatch.objects.get(id=pk)
        form = PostaldispatchForm(request.POST, request.FILES, instance=postaldispatch)
        if form.is_valid():
            form.save()
            messages.success(request,'Data update successfull',extra_tags='success')
            return redirect(reverse('frontoffice:postaldispatchs'))
    

class DeletePostaldispatchView(View):
    def get(self,request,pk):
        postaldispatch=Postaldispatch.objects.get(id=pk)
        postaldispatch.delete()
        messages.success(request,'Data delete successfull',extra_tags='success')
        return redirect(reverse('frontoffice:postaldispatchs'))

edubd/frontoffice/views/postalreceive.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.models import User, Group
from django.urls import reverse
from ..models import Postalreceive
from ..form import PostalreceiveForm
from django.contrib import messages
import datetime
from django.utils import formats


# Create your views here.

# Create your views here.

class PostalreceiveView(View):
    def get(self,request):
        postalreceive=Postalreceive.objects.all().order_by('-id')
        contex = {'postalreceive':postalreceive}
        return render(request, 'postalreceive/index.html',contex)

class AddPostalreceiveView(View):
    def get(self,request):
        form = PostalreceiveForm()
        context = {'form':form }
        return render(request, 'postalreceive/create.html',context)
    def post(self,request):
        postalreceive=request.POST
        form = PostalreceiveForm(request.POST, request.FILES) 
        if form.is_valid():
            postalreceive=form.save()
            messages.success(request,'Data store successfull',extra_tags='success')
            return redirect(reverse('frontoffice:postalreceives'))
    

class EditPostalreceiveView(View):
    def get(self,request,pk):
        postalreceive=Postalreceive.objects.get(id=pk)
        form = PostalreceiveForm(instance=postalreceive)
        context={'form':form}
        return render(request, 'postalreceive/create.html',context)
    def post(self,request,pk):
        postalreceive=Postalreceive.objects.get(id=pk)
        form = PostalreceiveForm(request.POST, request.FILES, instance=postalreceive)
        if form.is_valid():
            form.save()
            messages.success(request,'Data update successfull',extra_tags='success')
            return redirect(reverse('frontoffice:postalreceives'))
    

class DeletePostalreceiveView(View):
    def get(self,request,pk):
        postalreceive=Postalreceive.objects.get(id=pk)
        postalreceive.delete()
        messages.success(request,'Data delete successfull',extra_tags='success')
        return redirect(reverse('frontoffice:postalreceives'))

edubd/frontoffice/templates/visitorbook/camera.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webcam</title>
</head>
<body>
   
    <video id="video" autoplay></video>
    <canvas id="canvas" ></canvas><br>
    <button onclick="snap()"> Capture</button>
    <script>
        var video = document.getElementById('video');
        var canvas = document.getElementById('canvas');
        var context = canvas.getContext('2d');
        navigator.mediaDevices.getUserMedia({
            video:true
        })
        .then(stream => {
            document.getElementById('video').srcObject = stream;
        })

        function snap(){
            canvas.width = video.clientWidth;
            canvas.height = video.clientHeight;
            context.drawImage(video, 0 ,0);
        }
    </script>
    <!-- <canvas id="canvas"></canvas><br>
    <button onclick="snap()"> Capture</button>

    <script>
        var video = document.getElementById('video');
        var canvas = document.getElementById('canvas');
        var context = canvas.getContext('2d');

        navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || avigator.oGetUserMedia || avigator.msGetUserMedia;

        if(navigator.getUserMedia){
            navigator.getUserMedia({video:true}, streamWebCam, throwError);
        }

        function streamWebCam (stream){
            video.src = window.URL.createObjectURL(stream);
            video.play();
        }
        function throwError(e){
            alert(e.name);
        }

        function snap(){
            canvas.width = video.clientWidth;
            canvas.height = video.clientHeight;
            context.drawImage(video, 0 ,0);
        }
    </script> -->
</body>
</html>

edubd/frontoffice/templates/visitorbook/create.html
{%  extends 'author/base.html' %}

{% block content %}

		<br>

		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card card-body">
					<h5>Visitor Book</h5>
				</div>
				<div class="card card-body">
					<form action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="row">
							<div class="col-md-4">
								<video  id="video" autoplay></video><br>
								<button class="btn btn-primary btn-block" type="button" onclick="snap()"> Capture</button>
							</div>
							<div class="col-md-4">
								<canvas id="canvas" height="250px" width="250px" ></canvas>
							</div>
							<div class="col-md-4" >
							<div id="text" style="display:none">
							<div  style="background: #FF5733; color: #fff; padding: 25px 8px 0; height: 250px; ">
								<h4 > Click right button over the picture and click on the save image as</h4>
								</div>
								</div>
							</div>
							
							
							<div class="col-md-6">
								<div class="form-group">
									<label for="exampleInputEmail1">Name</label>
									{{form.name}}
									<span class="text-danger">{{form.errors.name}}</span>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="exampleInputEmail1">Phone</label>
									{{form.phone}}
									<span class="text-danger">{{form.errors.phone}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Purpose</label>
									{{form.purpose}}
									<span class="text-danger">{{form.errors.purpose}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Meet User Type</label>
									{{form.meet_user_type}}
									<span class="text-danger">{{form.errors.meet_user_type}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Meet User</label>
									
									{% if check == 1 %}
											{{form.meet_user}}
										{% else %}
											<select name="meet_user" class="form-control select2 "  required="" id="id_meet_user" >
										

											</select>
										{% endif %}
									<span class="text-danger">{{form.errors.meet_user}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Date</label>
									{{form.date}}
									<span class="text-danger">{{form.errors.date}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">In Time</label>
									{{form.in_time}}
									<span class="text-danger">{{form.errors.in_time}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Out Time</label>
									{{form.out_time}}
									<span class="text-danger">{{form.errors.out_time}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">ID Card</label>
									{{form.id_card}}
									<span class="text-danger">{{form.errors.id_card}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Attachment</label>
									{{form.attachment}}
									<span class="text-danger">{{form.errors.attachment}}</span>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="exampleInputEmail1">Image</label>
									{{form.image}}
									<span class="text-danger">{{form.errors.image}}</span>
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<label for="exampleInputEmail1">Note</label>
									{{form.note}}
									<span class="text-danger">{{form.errors.note}}</span>
								</div>
							</div>
						</div>
						<button type="submit" class="btn btn-success">Submit</button>
					</form>
				</div>
			</div>
			
		</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		
<script>
	$(document).ready(function() {
		$("#id_meet_user_type").change(function(){
			var id = $(this).val();
			console.log(id);
			$.ajax({
				type:'GET',
				url:'{% url 'frontoffice:get_user' %}',
				data:{id:id},
				success:function(data){
					console.log(data);
					$('#id_meet_user').html(data)
				},
				error:function(){
					console.log('error');
				}
			});
		});
	});
</script>
<script>
        var video = document.getElementById('video');
        var canvas = document.getElementById('canvas');
        var context = canvas.getContext('2d');
        navigator.mediaDevices.getUserMedia({
            video:{
				width:260,
				height:250
			}
        })
        .then(stream => {
            document.getElementById('video').srcObject = stream;
        })

        function snap(){
            canvas.width = video.clientWidth;
            canvas.height = video.clientHeight;
            context.drawImage(video, 0 ,0);
			document.getElementById('text').style='display:block'
        }
    </script>
{% endblock content %}

edubd/frontoffice/templates/visitorbook/detail.html
{% extends "author/base.html" %}
{% load static %}
{% block content %}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<h5>Visitor Book:</h5>
		
		
		<hr>
		<div class="card card-header">
		<h1>Visitor Book Details</h1>
		</div>
		<div class="card card-body">
			<div class="row">
				<div class="col-md-6"> 
					<ul class="list-group">
						<li class="list-group-item "><span class="font-weight-bold">{{visitorbook.name}} </span><span class="float-right"><img width="100px" height="100px" class="profile-pic" src="{{visitorbook.image.url}}" ></span></li>
						<li class="list-group-item "><span class="font-weight-bold">Purpuse : </span><span class="float-right">{{visitorbook.purpose}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">Phone No : </span><span class="float-right">{{visitorbook.phone}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">Id Card : </span><span class="float-right">{{visitorbook.id_card}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">Atachment : </span><span class="float-right">{% if visitorbook.attachment %}
								<a class="badge badge-info" href="/static/images/{{visitorbook.attachment}}" target="_blank">Attachment</a>

							{% else %}
								None
							{% endif %}</span>
						</li>
						
						
						
					</ul>
				</div>
				<div class="col-md-6"> 
					<ul class="list-group">
						<li class="list-group-item "><span class="font-weight-bold">Meet User Type : </span><span class="float-right">{{visitorbook.meet_user_type}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">Meet user : </span><span class="float-right">{{visitorbook.dmeet_user}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">Date : </span><span class="float-right">{{visitorbook.date|date:'d-m-Y'}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">In Time : </span><span class="float-right">{{visitorbook.in_time}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">Out Time : </span><span class="float-right">{{visitorbook.out_time}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">Phone No : </span><span class="float-right">{{visitorbook.phone}}</span></li>
						<li class="list-group-item "><span class="font-weight-bold">Atachment : </span><span class="float-right">{% if visitorbook.attachment %}
								<a class="badge badge-info" href="/static/images/{{visitorbook.attachment}}" target="_blank">Attachment</a>

							{% else %}
								None
							{% endif %}</span>
						</li>
						
						
						
					</ul>
				</div>
				
				<div class="col-md-12" style="padding-top:20px;"> 
					<ul class="list-group">
						<li class="list-group-item active">Note</li>
						<li class="list-group-item ">{{visitorbook.note}}</li>
					</ul>
				</div>
				
				
			</div>
		</div>
	</div>

	

</div>
  
{% endblock  %}

edubd/frontoffice/templates/visitorbook/get_user.html
<option value="">Select</option>
{% for row in users  %}
    <option value="{{row.id}}">{{row.first_name}}</option>
{% endfor %}

edubd/frontoffice/templates/visitorbook/index.html
{% extends "author/base.html" %}

{% block content %}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<h5>:</h5>
		
		
		<hr>
		<div class="card card-header">
		<h1>Visitor Book
			<a class="btn btn-primary  float-right" href="{% url 'frontoffice:add_visitorbook' %}"> + Add Visitor Book</a></h1>
		</div>
		<div class="card card-body"> 
			<table class="table table-sm">
				<tr>
					<th>Serial</th>
					<th>Picture</th>
					<th>Name</th>
					<th>Purpose</th>
					<th>Phone</th>
					<th>ID Card</th>
					<th>Date</th>
					<th>Meet User</th>
					<th>Action</th>
				</tr>
				{% for row in visitorbook  %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td><img width="50px" height="50px" class="profile-pic" src="{{row.image.url}}" ></td>
						<td>{{row.name}}</td>
						<td>{{row.purpose}}</td>
						<td>{{row.phone}}</td>
						<td>{{row.id_card}}</td>
						<td>
							<span class="font-weight-bold">Date: </span> {{row.date|date:'d-m-Y'}}, <br>
							<span class="font-weight-bold">In time: </span> {{row.in_time}}, <br>
							<span class="font-weight-bold">Out time: </span> {{row.out_time}}, <br>
						</td>
						<td>
							<span class="font-weight-bold">User Type: </span> {{row.meet_user_type}}, <br>
							<span class="font-weight-bold">Name: </span> {{row.meet_user}}, <br>
							<span class="font-weight-bold">Phone: </span> {{row.phone}}, <br>
						
						</td>
						
						<td>
						
						<a href="{% url 'frontoffice:visitorbook' row.id %}" class="btn btn-info"><i class="fa fa-eye"></i></a>
						<a href="{% url 'frontoffice:edit_visitorbook' row.id %}" class="btn btn-success"><i class="fa fa-edit"></i></a>
						<a onclick='return confirm("Are you sure you want to do this?")' href="{% url 'frontoffice:delete_visitorbook' row.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a></td>
					</tr>
				{% endfor %}

			</table>
		</div>
	</div>

	

</div>
  
{% endblock  %}